name: 1-Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "Please specify the environment (OS, version, etc.)"
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of JDK is applied in the development?
      options:
        - latest (Default)
        - JDK 20
        - JDK 17
        - JDK 11
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Where are you seeing the problem on?
      multiple: true
      options:
        - Console
        - Terminal
        - Browsers
        - Others
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/linphone-40685558/group3-coursework/blob/master/codeOfConduct.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
